version: '3'

services:
  nuxt:
    build: .
    tty: true
    command: npm run dev
    volumes:
      - .:/mens_cosme_web
    ports:
      - "3000:3000"

  web:
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - nuxt